services:
  angular:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: layar-tancap
    restart: unless-stopped
    ports:
      - "4400:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s